version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/server"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "pub"
    directory: "/client"
    schedule:
      interval: "weekly"  
