name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.7.7'

    - name: Flutter Lint
      run: flutter analyze

    - name: Flutter Build
      run: flutter build

    - name: Flutter Test
      run: flutter test
