name: Flutter CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.7.7'
        
    - name: Get packages
      run: flutter pub get
      working-directory: ./client
      
    - name: Build app
      run: flutter build apk
      working-directory: ./client
