name: Flutter Build Check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.7.7'
    - name: Get packages
      run: flutter pub get
    - name: Build app
      run: flutter build apk