name: Node.js CI

on:
  push:
    branches: ["master", "dev"]
  pull_request:
    branches: ["master", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: 'server'
      - name: Use Node.js 19.x
          working-directory: ./server
          uses: actions/setup-node@v3
          wirh:
            node-version: ${{ matrix.node-version }}
            cache: "npm"
            cache-dependency-path: ./server/package-lock.json
      - name: install dependencies
        run: npm ci 
        working-directory: ./server
      - run: npm run build --if-present
        working-directory: ./server
